### PR TITLE
Dont chrash on validation error

### PR DESCRIPTION
**Pull request by smoli**
I'm using your tool to learn how to program wgpu-shaders. I added some code to prevent the app from crashing when the fragment shader cannot be compiled.

Thanks for making this.

### CODE REVIEW

**Comment by paulgb** [comment]
Thanks for this. The code looks good, I just want to give it a try before committing and I temporarily broke the setup I use for testing this, will merge as soon as I fix that.

**Review by paulgb — APPROVED** [review]
Finally fixed my environment and tested this. This is great, thank you!

**Comment by paulgb** [comment]
Published to crates.io as 0.1.6.

**Comment by smoli** [comment]
Thank you!

**Pull request merged**
